# Generated by Django 4.2.4 on 2023-08-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_rename_create_att_record_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
